//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bambu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public int hor_ident { get; set; }
        public int hor_orden { get; set; }
        public string hor_dia1 { get; set; }
        public string hor_activ1 { get; set; }
        public string hor_horin1 { get; set; }
        public string hor_horfi1 { get; set; }
        public string hor_color1 { get; set; }
        public string hor_dia2 { get; set; }
        public string hor_activ2 { get; set; }
        public string hor_horin2 { get; set; }
        public string hor_horfi2 { get; set; }
        public string hor_color2 { get; set; }
        public string hor_dia3 { get; set; }
        public string hor_activ3 { get; set; }
        public string hor_horin3 { get; set; }
        public string hor_horfi3 { get; set; }
        public string hor_color3 { get; set; }
        public string hor_dia4 { get; set; }
        public string hor_activ4 { get; set; }
        public string hor_horin4 { get; set; }
        public string hor_horfi4 { get; set; }
        public string hor_color4 { get; set; }
        public string hor_dia5 { get; set; }
        public string hor_activ5 { get; set; }
        public string hor_horin5 { get; set; }
        public string hor_horfi5 { get; set; }
        public string hor_color5 { get; set; }
        public string hor_dia6 { get; set; }
        public string hor_activ6 { get; set; }
        public string hor_horin6 { get; set; }
        public string hor_horfi6 { get; set; }
        public string hor_color6 { get; set; }
        public string hor_salon { get; set; }
    }
}
