//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bambu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class novedade
    {
        public int nov_ident { get; set; }
        public int nov_nuimg { get; set; }
        public string nov_titulo { get; set; }
        public string nov_descr { get; set; }
        public string nov_imagen { get; set; }
        public string nov_titulo2 { get; set; }
    }
}
