//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bambu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class principal
    {
        public int pri_ident { get; set; }
        public int pri_nusec { get; set; }
        public string pri_secci { get; set; }
        public string pri_imagen { get; set; }
    }
}
